version: '2'

services:
  db:
    #window,linux用这里
    image: mysql:5.7
    #only use for linux and mac
    ports:
      - "3306"
    volumes:
      - ~/dockerShare/mysql/namechoose:/var/lib/mysql
    env_file:
      - ./env/mysql.env
    environment:
      - "TZ=Asia/Shanghai"

  namechoose:
    build: ./
    image: haifeng/namechoose:latest
    ports:
      - "8888:8080"
    links:
      - db:db
    env_file:
      - ./env/mysql.env
    environment:
      TZ: Asia/Shanghai